# Generated by Django 3.1.2 on 2020-11-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone Number')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_agency', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='districts.district')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
