# Generated by Django 3.1.2 on 2020-11-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Spot Name')),
                ('type', models.CharField(max_length=50, verbose_name='Spot Type')),
                ('description', models.CharField(max_length=2000, verbose_name='Spot Description')),
                ('full_address', models.CharField(max_length=1000, verbose_name='Full address')),
                ('geoLat', models.FloatField(default=0, verbose_name='Latitude')),
                ('geoLon', models.FloatField(default=0, verbose_name='Longitude')),
                ('geoLocationSet', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.district')),
            ],
        ),
        migrations.CreateModel(
            name='SpotReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=3000, verbose_name='Spot Review')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='User Rating')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Review Time')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spots', verbose_name='Spot Image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Image Added')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.spot')),
            ],
        ),
    ]
