# Generated by Django 3.1.2 on 2020-11-30 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spots', '0002_auto_20201130_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Hotel Name')),
                ('hotel_type', models.CharField(max_length=50, verbose_name='Hotel Type')),
                ('hotel_description', models.CharField(max_length=2000, verbose_name='Hotel Description')),
                ('hotel_full_address', models.CharField(max_length=1000, verbose_name='Full address')),
                ('available_rooms', models.IntegerField(verbose_name='Available Rooms')),
                ('per_unit_price', models.IntegerField(verbose_name='Per Unit Price')),
                ('geoLat', models.IntegerField(default=0, verbose_name='Latitude')),
                ('geoLon', models.IntegerField(default=0, verbose_name='Longitude')),
                ('geoLocationSet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_review', models.CharField(max_length=3000, verbose_name='Hotel Review')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Review Time')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='User Rating')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_image', models.ImageField(upload_to='spots', verbose_name='Hotel Image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Review Time')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.hotel')),
            ],
        ),
    ]
