# Generated by Django 3.1.2 on 2020-12-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_hotel_hotelimages_hotelreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotreview',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='spots.spot'),
        ),
    ]
