# Generated by Django 3.1.2 on 2020-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_auto_20201220_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(verbose_name='booked date'),
        ),
    ]
